export const initialData: any = [
  {
    id: 1,
    title: "Sample Todo 1",
    deadline: new Date(),
    status: "active",
    priority: "High",
    order: 1,
  },
  {
    id: 2,
    title: "Sample Todo 2",
    deadline: new Date(),
    status: "active",
    priority: "Medium",
    order: 2,
  },
  {
    id: 3,
    title: "Sample Todo 3",
    deadline: new Date(),
    status: "active",
    priority: "Low",
    order: 3,
  },
  {
    id: 4,
    title: "Sample Todo 4",
    deadline: new Date(),
    status: "completed",
    priority: "High",
    order: 4,
  },
  {
    id: 5,
    title: "Sample Todo 5",
    deadline: new Date(),
    status: "completed",
    priority: "Medium",
    order: 5,
  },
  {
    id: 6,
    title: "Sample Todo 6",
    deadline: new Date(),
    status: "completed",
    priority: "Low",
    order: 6,
  },
];
